### ISSUE TITLE
"Has Role" feature in the API/Config

### ISSUE THREAD

**Issue by StrangeOne101** [StrangeOne101/Iroh#8]
# Description
The config needs a new section where roles can be defined by plain text, and these can then be checked in code later on. For example, in the config, we might have:
```json
"Roles": {
    "staff": [
        "414878520028954630",
        "300692373254569984"
    ]
}
```
Then in the code for a command we might have
```js
if (!API.hasRole(member, "staff")) {
    message.reply("You don't have permission to run this command!");
    return;
}
```

**Comment by geniusjam** [comment]
Are the IDs in the example role IDs or user IDs?
Also, may I be assigned this issue?

**Comment by StrangeOne101** [comment]
> Are the IDs in the example role IDs or user IDs?
> Also, may I be assigned this issue?

Good question. They are role IDs. And sure 👍

**Comment by geniusjam** [comment]
Is it required that the member has to have all of the roles specified, or is it sufficient that they have any of them?

**Comment by StrangeOne101** [comment]
Any of them. It's more so that we can specify a "staff" internal role for example that has the role IDs for say, moderator, developer, admin, etc
